name: Validate API Spec

on:
  push:
  workflow_dispatch: 

jobs:
  generated:
    name: Update generated files
    runs-on: ubuntu-latest
    steps:
      # By default, when you use actions/checkout on a PR, it will checkout the 
      # head commit in a detached head state. If you want to make some changes, 
      # you have to checkout the branch the PR is coming from in the head repo.
      #
      # https://github.com/EndBug/add-and-commit#working-with-prs
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        if: github.event_name == 'pull_request'
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install NPM Dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Regenerate
        run: |
          yarn generate
      - name: Commit changes (if any)
        uses: EndBug/add-and-commit@v9
        with:
          add: 'generated/'
          message: 'chore: update generated files'
          committer_name: GitHub Actions
          committer_email: actions@github.com
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated
          path: generated/
  # Cannot be enabled until we merge to this to main
  #
  # diff-spec:
  #   name: Prevent Breaking Changes
  #   runs-on: ubuntu-latest
  #   needs: [generated]
  #   steps:
  #     - name: Check out head branch
  #       uses: actions/checkout@v2
  #       with:
  #         path: head
  #     - name: Check out main branch
  #       uses: actions/checkout@v2
  #       with:
  #         ref: main
  #         path: base
  #     - name: Download generated artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: generated
  #         path: head/generated/
  #     - name: Check v1beta
  #       uses: mvegter/openapi-diff-action@v0.23.5
  #       with:
  #         head-spec: head/generated/spec/v1beta.json
  #         base-spec: base/generated/spec/v1beta.json
  #     - name: Check v1
  #       uses: mvegter/openapi-diff-action@v0.23.5
  #       with:
  #         head-spec: head/generated/spec/v1.json
  #         base-spec: base/generated/spec/v1.json
  lint-spec:
    name: Lint
    runs-on: ubuntu-latest
    needs: [generated]
    steps:
      - uses: actions/checkout@v3
      - name: Download generated artifacts
        uses: actions/download-artifact@v3
        with:
          name: generated
          path: generated/
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install NPM Dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
